version: '2.3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    hostname: localhost
    build: ''
    ports:
      - 8899:80
  mock: #name of the second service
    build: json-server # specify the directory of the Dockerfile
    ports:
      - '3000:3000' #specify ports forewarding
